### ISSUE TITLE
Новый Хром 56 виснет на скрипте Антицензорити

### ISSUE THREAD

**Issue by ilyaigpetrov** [anticensorship-russia/chromium-extension#6]
25.01.2017 [вышел](https://chromereleases.googleblog.com/2017/01/stable-channel-update-for-desktop.html) Хром 56.

К сожалению, он плохо работает с PAC-скриптом Антицензорити, пожирая всю доступную память.

![V8 Proxer Resolver eats memory](http://i.imgur.com/bdNie7j.jpg)

### Временное решение

Используйте пока альтернативный скрипт __Антизапрет__ в настройках расширения:

1. Клик по синей ленте.
2. Выбрать Антизапрет.

Вы также можете [пересесть на FireFox](https://rebrand.ly/ac-anticensority).

Я автоматически перевожу всех пользователей на PAC-скрипт Антизапрет через срочное обновление расширения.

**Comment by ilyaigpetrov** [comment]
Поставьте, пожалуйста, звезду на https://crbug.com/639217  

После того, как этот баг будет исправлен, я смогу починить PAC-скрипт Антицензорити в расширении, пусть и в следующей версии Хрома.

**Comment by stamepicmorg** [comment]
Отлично, у этих задач статус Fixed.

**Comment by ilyaigpetrov** [comment]
Спасибо всем за поддержку, баг был исправлен в репозитории Chromium за 2 дня!

В стабильный Хром 57 исправления могут попасть только в следующем релизе в марте.
Возможно чуть раньше появятся в Chrome Canary.

До тех пор вы можете использовать Антизапрет с Хромом или [Антицензорити для Firefox](https://rebrand.ly/ac-anticensority).

**Comment by pavel-shvetsov** [comment]
В Chrome 56.0.2924.76 (64-bit) под Ubuntu 14.04 не баг не проявляется

**Comment by mikhaelkh** [comment]
Вышел Chrome 57. Если у него всё нормально, тему можно закрыть.

**Comment by ilyaigpetrov** [comment]
За два дня тестирования тормозов не наблюдалось, жалоб нет -- закрываю тему.  
Клеймо "тормозит" будет снято, когда большинство пользователей переберётся на хром 57 или будет отображаться только на Хром 56.  
Ещё раз всем спасибо.

**Comment by stamepicmorg** [comment]
Хром - Версия 58.0.3029.110, май 18го. Все еще присутствует надпись "тормозит". Пока решили не убирать?

Полет нормальный.

**Comment by ilyaigpetrov** [comment]
> Пока решили не убирать?

1. [Некоторые](https://www.neverware.com) дистрибутивы тормозят с обновлением Хрома, потому я поддерживаю три последние версии Хрома (58, 57, 56).
2. Опубликованная версия достаточно стабильна, и уже давно не было повода для обновления.
