### ISSUE TITLE
Использовать только Tor для проксирования

### ISSUE THREAD

**Issue by PekaFat** [anticensorship-russia/chromium-extension#7]
Привет, почему нельзя использовать исключительно Tor для проксирования сайтов, без использования каких-либо pac-скриптов? А нужные сайты вручную добавить в исключениях.

**Comment by ilyaigpetrov** [comment]
Верно ли я понял, что вы хотите проксировать несколько сайтов, добавленных вручную, через Tor?
Использовать только Tor для проксирования без прокси из PAC-скриптов можно так:
1. [x] использовать свой локальный TOR
2. [ ] использовать прокси PAC-скрипта

**Comment by PekaFat** [comment]
Да, так работает, но список сайтов всё равно подгружается из pac-скрипта, а я имел ввиду чтобы вообще отключить pac-скрипты и прописать нужные мне сайты вручную.

**Comment by ilyaigpetrov** [comment]
Да, я могу реализовать такую функцию в одной из следующих версий, но только если своих сайтов будет до 10-15 штук, иначе управлять большим списком сайтов будет просто неудобно и может быть неэффективно в плане производительности.

**Comment by ilyaigpetrov** [comment]
Реализовано в только что опубликованной версии 0.27.  
`chrome://extensions > режим разработчика > обновить расширения`  
Можно протестировать и оставить отзыв.

**Comment by PekaFat** [comment]
Работает, но не хватает списка уже добавленных сайтов и чтобы в этот же список добавлять нужные сайты в будущем.

**Comment by ilyaigpetrov** [comment]
Как я понял, нужно, чтобы список уже добавленных сайтов можно было переносить с компьютера на компьютер 1) копированием-вставкой или даже 2) через синхронизацию настроек с аккаунтом гугл.
Верно я понял, что нужны 1) и 2), и 1) -- в приоритете?

**Comment by PekaFat** [comment]
Да.

**Comment by PekaFat** [comment]
А ещё вопрос, что в описании "запретить опредление по IP/DNS" значит:
> Используйте, если вам кажется, что мы проксируем слишком много сайтов. 

?

**Comment by ilyaigpetrov** [comment]
PAC-скрипт не сможет определять заблокированный сайт по IP-адресу, только по доменному имени.  
В итоге, сайтов будет проксироваться меншье, а PAC-скрипт может работать чуть быстрее.

**Comment by PekaFat** [comment]
> Как я понял, нужно, чтобы список уже добавленных сайтов можно было переносить с компьютера на компьютер 1) копированием-вставкой или даже 2) через синхронизацию настроек с аккаунтом гугл.
> Верно я понял, что нужны 1) и 2), и 1) -- в приоритете?

Есть примерные сроки обновления?

**Comment by ilyaigpetrov** [comment]
Попробую успеть на выходных сделать следующее:

1. По кнопке будет открываться textarea, в которой будет два списка: включённые и исключённые из проксирования сайты.
2. Списки будут в одной textarea, а не в вдух, чтобы можно было использовать copy-paste один раз для переноса настроек (откуда-нибудь из интернета, к примеру).
3. Один список будет отделён от другого каким-нибудь простым синтаксисом, например:
```
список_включённых (одна строка -- один хост)
одна_пустая_строка
список_исключённых (одна строка -- один хост)
```

Я не думал, что задача для вас приоритетна, ведь не часто настраиваешь только что установленное расширение. Чтобы я лучше понимал необходимый функционал, вы можете а) описать контекст задачи и б) указать, что для вас приоритетней. Например, а) "я содержу парк машин и мне нужно синхронизировать исключения между ними, но не через гугл-аккаунт", или б) "для меня приоритетеней только copy-paste, синхронизация через google-аккаунт мне не нужна".

**Comment by PekaFat** [comment]
Я хочу просто указать список сайтов на которых будет включено проксирование и в принципе всё.
Простой копи-паст подойдёт идеально.

**Comment by ilyaigpetrov** [comment]
Релизовано в версии 0.28 -- протестируйте, пожалуйста.  
`chrome://extensions` > Режим разработчика > Обновить расширения.

**Comment by PekaFat** [comment]
Работает, спасибо!
