### ISSUE TITLE
ipleak.net багает расширение

### ISSUE THREAD

**Issue by PekaFat** [anticensorship-russia/chromium-extension#8]
При заходе на https://ipleak.net сначала расширение показывает, что прокси используется, а при обновлении страницы - красные цифры со значка пропадают и показывается мой настоящий ip адрес.

Как воспроизвести:
1. Отключить все расширения, кроме "Обход блокировок Рунета"
2. Настроить:
![image](https://cloud.githubusercontent.com/assets/13280748/24386466/bff14384-1380-11e7-84e6-b3cc7fcd3d49.png)
3. Добавить ipleak.net в исключения
4. Зайти на https://ipleak.net
5. Может сразу показать ваш реальный ip, а может сначала ip прокси (тора)
6. При обновлении страницы будет показан реальный ip
7. Расширение перестаёт работать на всех сайтах и помогает только перезапуск (снять-включить галочку в настройках расширений хрома)

На https://2ip.ru всегда показывает ip прокси и такого бага нет.
Попробовал с Proxy SwitchyOmega - там такого тоже нет, показывает ип прокси всегда.

Версия расширения 0.0.0.28

**Comment by ilyaigpetrov** [comment]
1. Возможно, что прокси на localhost (или Тор) иногда отказывают в проксировании. При отказе Хром заносит их временно в чёрный список и проксирование перестаёт работать, если нет альтернативных прокси. Подумаю, что можно сделать.
2. Ошибка с тем, что _"только шифрованная связь с прокси"_ приводила к отключению всех прокси (*facepalm*) исправлена в версии 0.29.

**Comment by ilyaigpetrov** [comment]
Предположительно, происходит следующее:

1. ipleak.net далает какие-то запросы, которые могут нарушать приватность пользователя и Тор отказывается их проксировать.
2. Хром заносит Тор на localhost'е в чёрный список (`chrome://net-internals/#proxy`).
3. Хром начинает использовать прямое подключение к ipleak.net, т.к. других прокси не осталось.

Что можно сделать. Я могу добавить опцию _"проксируй или умри!"_ (или _"всё или ничего"_): при отказе прокси Хром не сможет делать прямое подключение и будет вынужден выдавать отказ пользователю или заново пробовать прокси (даже из чёрного списка).

Как вам такое решение?

**Comment by ilyaigpetrov** [comment]
Сейчас наше расширение работает так:

1. Если все прокси отказали, то пробуется соединение напрямую без прокси.

С флагом _"Проксируй или умри!"_ будет работать так:

1. Если все прокси отказали, то блокировать запрос и вернуть ошибку.

SwitchyOmega по умолчанию работает в режиме _"Проксируй или умри!"_.

**Comment by PekaFat** [comment]
> Как вам такое решение?

Было бы отлично.

**Comment by ilyaigpetrov** [comment]
Есть бета-версия, буду тестировать до Вс.  
Можете принять участие в тесте, прислав [мне](github.com/ilyaigpetrov/) ваш google-аккаунт, на который завязан Хром.

**Comment by ilyaigpetrov** [comment]
Опция _"Проксируй или умри"_ добавлена в 0.30 и включена по умолчанию.
